name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  ci:
    if: github.event_name == 'pull_request'
    uses: RobbyPrograms/apple-workflows/.github/workflows/go-ci.yml@main
    with:
      service-name: svc-inventory